### PR TITLE
Add how to install in README

### PR DESCRIPTION
**Pull request by devRMA**
Fix the issue #61

### CODE REVIEW

**Comment by JulienPalard** [comment]
I often see this `--upgrade`/`-U` flag in the install line, but I don't really like it, as it's a bit of a lie, it's not the command to install, it's the command to install or upgrade, but I don't expect users reading this line to need the `--ugrade` part.

Is there a real use-case I am missing behind this?

**Comment by devRMA** [comment]
> I often see this `--upgrade`/`-U` flag in the install line, but I don't really like it, as it's a bit of a lie, it's not the command to install, it's the command to install or upgrade, but I don't expect users reading this line to need the `--ugrade` part.
> 
> Is there a real use-case I am missing behind this?

I used as a base, the README of this repository.
https://github.com/Rapptz/discord.py#installing
I honestly don't know the difference between using the -U flag or not, I just put it, because in the discord.py repository, the installation example taught like that, but I can remove that part.

**Comment by JulienPalard** [comment]
Back from holidays!

As we both don't see a good reason to use `-U`, yes, please remove it.

If in the future we see a good reason to add it it can be added with a commit message explaining why it's added, which I prefer.

**Comment by devRMA** [comment]
> Back from holidays!
> 
> As we both don't see a good reason to use `-U`, yes, please remove it.
> 
> If in the future we see a good reason to add it it can be added with a commit message explaining why it's added, which I prefer.

ok

**Comment by JulienPalard** [comment]
:+1: thanks for the PR!

And happy holidays!!

**Pull request merged**
