### PR TITLE
Feat/readme lazy evaluation

### PR DESCRIPTION
**Pull request by jerabaul29**
Illustrate that we do get lazy evaluation using this module.

### CODE REVIEW

**Comment by jerabaul29** [comment]
This is to document what is discussed in issue #68 : using this module, one does get lazy evaluation :) .

**Comment by JulienPalard** [comment]
Thanks for the PR! LGTM with nits (looks a bit long for the point): I'm not fan of using ic here as most people may test it using a REPL (and ic whines in an REPL). It will also save two line in the example, maybe use the debug-mode of f-strings? Like:

```python
print(f"What happens when we force evaluation: {list(res_with_list)=}")
```

for better readability you can get "it prints" out of the python bloc, and put the print result in a text block following it.

Also maybe you can use `count()` from itertools as a source instead of `range(100)`, it's a good proof everything is lazy ;)

**Comment by jerabaul29** [comment]
Better like this? :)

**Comment by JulienPalard** [comment]
Works for me :) Thanks for the PR !! :)

**Pull request merged**
