### PR TITLE
Introduce matrix transposition and intersect functions

### PR DESCRIPTION
**Pull request by safwank**

### CODE REVIEW

**Comment by JulienPalard** [comment]
What is the advantage of pipe.intersect over the intersect operator (``&``) on `set` ?

I mean, how:

    count() | select(lambda x: x ** 2) | take(10) | intersect(
        count() | select(lambda x: x * 2) | take(10))

is more readable than:

    set(count() | select(lambda x: x ** 2) | take(10)) &
        set(count() | select(lambda x: x * 2) | take(10))

**Comment by safwank** [comment]
Hi @JulienPalard,

I wasn't aware of the & operator considering I'm just an amateur Python programmer and more familiar with Haskell and Elixir. To answer your question, it's not necessarily more readable. However, I personally deal mostly with lists than sets, so having to convert it to the latter seems a bit unnecessary.

**Comment by JulienPalard** [comment]
However, i'll gladly merge your transpose function.

**Comment by safwank** [comment]
That'd be good, thanks.

**Comment by JulienPalard** [comment]
I merged the "transpose" commit, thanks for your contribution and sry for the delay (I ever missed the PR birthday).

**Pull request closed without merging**
