### PR TITLE
Setup Python version matrix for GHA

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by JulienPalard** [comment]
If I get it right, your change make github start 4 runners, each of them installs tox and run tox (each with one single Python version to test), instead of starting a single runner, installing tox once, and having tox test with the 4 different Python version?

**Comment by gliptak** [comment]
yes, above is great summary

**Comment by JulienPalard** [comment]
> yes, above is great summary

Is it any better? I feel like having to spawn a single runner is lighter than having to spawn three.

**Comment by gliptak** [comment]
I see more isolation the better in various testing setups ensuring that fails are quickly attributable. while there is overhead for the multiple spawns, overall runtime would be very similar

https://github.com/JulienPalard/Pipe/actions/runs/4378790944 1 min 50 sec
https://github.com/gliptak/Pipe/actions/runs/6962332242 59 sec

**Comment by JulienPalard** [comment]
Your solution has less lines than mine, which is nice too.

**Comment by JulienPalard** [comment]
Thanks!

**Pull request merged**
