### PR TITLE
Add "do" pipe

### PR DESCRIPTION
**Pull request by mhsekhavat**
Name `do` is inspired by [similar function](http://toolz.readthedocs.io/en/latest/api.html#toolz.functoolz.do) implemented in pytoolz library.

### CODE REVIEW

**Comment by JulienPalard** [comment]
There's already `| tee` for debugging purposes, does `| do()` is really usefull to do something else?

**Comment by mhsekhavat** [comment]
Some of other use cases that I myself want are calling logger.log and Path('cache_file').write_text

**Comment by mhsekhavat** [comment]
Another note about `tee` is that requires its input to be iterable.

**Comment by JulienPalard** [comment]
~Every command require their input to be an iterable, and alomost all of them return a generator. Your current of `| do(print)` won't work on them, typically:

    range(10) | select(lambda x: x % 2) | do(print)
will print something like `<generator ...>`, which is probably not what you want. Also if you give a function to your `do` that consumes the generator, it will be the last one of the pipe as the generator will end-up empty.

That's why tee, as its name kind of indicates it, duplicates the content of the generator : One for stdout and one for the next pipe instruction.

Why not implementing it like this:

```
@Pipe
def do(iterable, visitor):
    for item in iterable:
        visitor(item)
        yield item
```

But it would look like tee, so why not implementing it like this:

```

@Pipe
def tee(iterable, visitor=print):
    for item in iterable:
        visitor(item)
        yield item
```

?

**Comment by JulienPalard** [comment]
Closing as inactive and conflicting.

**Pull request closed without merging**
