### PR TITLE
add enumerate() pipe

### PR DESCRIPTION
**Pull request by im-scared**

### CODE REVIEW

**Comment by JulienPalard** [comment]
Looks good to me. Did you implemented it because you first found a need for it?

**Comment by im-scared** [comment]
> Looks good to me. Did you implemented it because you first found a need for it?

I actually did, yeah! This implementation is a copy of the code I wrote in my own project. I actually have some code like this in my project:
```python
ORDER_LOOKUP = DATA | enumerate | map(lambda x: (x[1], x[0])) | as_dict
```

The `enumerate()` approach felt very natural for me in python, since the builtin version is often used as a `forEachWithIndex` type situation.

**Comment by JulienPalard** [comment]
OK!

Why not just using the builtin then? Looks like it works:

```python
>>> import builtins
>>> enumerate = Pipe(builtins.enumerate)
>>> list(range(10) | enumerate)
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]
>>> list(range(10) | enumerate())
[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9)]
>>> list(range(10) | enumerate(10))
[(10, 0), (11, 1), (12, 2), (13, 3), (14, 4), (15, 5), (16, 6), (17, 7), (18, 8), (19, 9)]
>>> list(range(10) | enumerate(start=10))
[(10, 0), (11, 1), (12, 2), (13, 3), (14, 4), (15, 5), (16, 6), (17, 7), (18, 8), (19, 9)]
```

**Comment by im-scared** [comment]
Oh! I don't know why I didn't consider that! XD

**Comment by JulienPalard** [comment]
Can you add something in the README about it too? In the [existing-pipes-in-this-module](https://github.com/JulienPalard/Pipe#existing-pipes-in-this-module) section.

**Comment by im-scared** [comment]
Oh good catch! Added ^w^

**Comment by JulienPalard** [comment]
Thanks!!!

**Pull request merged**
